name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28.0"
          gleam-version: "1.13.0"
          rebar3-version: "3"
      - name: Install dependencies
        run: gleam deps download
      - name: Get Repository Name
        run: |
          echo "GITHUB_REPO_NAME=$(echo ${{ github.repository }} | cut -d "/" -f 2)" >> $GITHUB_ENV
      - name: Print Repository Name
        run: |
          echo ${{ env.GITHUB_REPO_NAME }}
      - name: Add Repository Path
        run: |
          sed -i -e 's|Index -> "/"|Index -> "/${{ env.GITHUB_REPO_NAME }}/"|g' src/${{ env.GITHUB_REPO_NAME }}.gleam
      - name: Build app
        run: gleam run -m lustre/dev build ${{ env.GITHUB_REPO_NAME }} --minify --outdir=dist
      - name: Fixing Links
        run: |
          sed -i -e 's|href="/${{ env.GITHUB_REPO_NAME }}.css"|href="./${{ env.GITHUB_REPO_NAME }}.css"|g; s|src="/${{ env.GITHUB_REPO_NAME }}.js"|src="./${{ env.GITHUB_REPO_NAME }}.js"|g' dist/index.html
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4